feat：设计器增加帮助文档说明
opentiny/tiny-engine pull request #100
Opened 2023-11-22 01:48 UTC by lichunn

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-11-22 03:36 UTC, chilingling commented on packages/plugins/help/src/HelpIcon.vue
> +    color: #191919;
建议适配一下亮色和暗色主题

2023-11-22 03:36 UTC, chilingling commented on packages/plugins/i18n/src/Main.vue
> +      <a class="help-box" :href="docsUrl" target="_blank">
help box 这里很多代码以及样式是重复的，看看能不能抽离组件出来

2023-12-01 03:35 UTC, chilingling commented on packages/plugins/block/src/Main.vue
> +const docsUrl = 'https://opentiny.design/tiny-engine#/help-center/course/engine/3'
这里 docs url 是不是太分散了，看看是不是集中到 controller 合理一点？帮忙看看 @wenmine @hexqi @yaoyun8

2023-12-01 08:10 UTC, yaoyun8 commented on packages/common/index.js
> +import LinkButton from './component/LinkButton.vue'
如果这个组件是只用在跳转帮助文档，组件名称建议用更有意义的命名，比如说HelpLink，或者是LinkToHelp，仅供参考。

2023-12-01 08:12 UTC, ghost commented on packages/common/package.json
> +    "@opentiny/tiny-engine-common": "workspace:^1.0.0",
依赖列表中为啥有自己哦

2023-12-01 08:14 UTC, ghost commented on packages/design-core/src/DesignPlugins.vue
> +      if (item.id === 'EditorHelp') return
'EditorHelp'建议用常量定义，可以通过命名解释下是什么

2023-12-01 08:17 UTC, yaoyun8 commented on packages/plugins/block/src/Main.vue
> +const docsUrl = 'https://opentiny.design/tiny-engine#/help-center/course/engine/3'
我也建议统一管理，如果后面需要修改链接地址，可以少量修改。

2023-12-05 06:29 UTC, yaoyun8 submitted a review, later dismissed
LGTM

2023-12-06 06:52 UTC, chilingling approved these changes, later dismissed

2023-12-12 01:23 UTC, chilingling submitted a review, later dismissed

2023-12-12 01:49 UTC, yaoyun8 submitted a review, later dismissed
LGTM

2023-12-15 07:42 UTC, wenmine submitted a review, later dismissed

2023-12-15 07:47 UTC, yaoyun8 approved these changes, later dismissed
LGTM

2023-12-19 11:21 UTC, chilingling requested changes

2023-12-19 11:21 UTC, chilingling commented on packages/plugins/help/src/HelpIcon.vue
> +          v-for="(item, idx) in questionList"
`v-for` 声明和 `key` 属性声明放前面

2023-12-19 11:21 UTC, chilingling commented on packages/plugins/help/src/HelpIcon.vue
> +  left: calc(var(--base-nav-panel-width));
这里 `calc` 是不是没有用了？

2023-12-19 11:21 UTC, chilingling commented on packages/plugins/script/src/Main.vue
> +      flex-direction: row;
`flex-direction` 初始值就是 row，这里可以不声明

2023-12-19 11:21 UTC, chilingling commented on packages/common/component/LinkButton.vue
> +<script lang="jsx">
1. 这里 `lang=jsx` 是不是没什么用？
2. 这里可以写成 composition 风格的

2023-12-19 11:21 UTC, chilingling commented on packages/controller/src/useHelp.js
> +  return { helpState }
这里建议导出来方法。而不是直接 export 出来 state。
比如：
```javascript

const getDocsUrl = (docId) => {
  return helpState.docsUrl[docId]
}

const getBaseUrl = () => 'https://opentiny.design/tiny-engine'


export default () => ({
  getDocsUrl,
  getBaseUrl,
})
```

好处是其他插件就不需要关心这里的细节，只需要传入 id，就可以拿到 url，后续 useHelp 更改了其他插件也无需关心。

2023-12-26 07:20 UTC, wenmine approved these changes
LGTM

2023-12-26 11:31 UTC, chilingling approved these changes

2023-12-26 11:33 UTC, yaoyun8 approved these changes

2023-12-26 11:50 UTC, merged