fix：修复自定义属性新增功能
opentiny/tiny-engine pull request #108
Opened 2023-11-29 03:18 UTC by lizhijie429

English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Background and solution

### What is the current behavior?

图标未显示导致无法添加自定义属性
![image](https://github.com/opentiny/tiny-engine/assets/7768535/ede1c447-20c8-4bdf-b6a0-3259789459e4)

修复警告
![image](https://github.com/opentiny/tiny-engine/assets/7768535/c6f5960b-5391-4c27-9a9b-c96aa0735409)

Issue Number: N/A

### What is the new behavior?

鼠标移入之后的提示
![image](https://github.com/opentiny/tiny-engine/assets/7768535/0a2b349c-8b84-49ed-ba44-7fb00fe89434)
鼠标点击之后的效果
![image](https://github.com/opentiny/tiny-engine/assets/7768535/888620a9-49da-4206-bc70-7df1123b99e6)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2023-11-29 09:15 UTC, chilingling requested changes

2023-11-29 09:15 UTC, chilingling commented on packages/common/component/MetaHtmlText.vue
> +  <div>
不需要额外加一层 div

2023-11-29 09:15 UTC, chilingling commented on packages/common/component/MetaHtmlAttributes.vue
> +  <div>
不需要额外加一层 div

2023-11-29 09:17 UTC, chilingling commented
欢迎 PR！🎉

2023-11-29 09:27 UTC, lizhijie429 commented on packages/common/component/MetaHtmlText.vue
> +  <div>
不加额外加这一层 div，报下面的这个警告，打开控制台调试，全是这个警告。
![image](https://github.com/opentiny/tiny-engine/assets/7768535/43334124-a10d-41c9-8099-337fa3e14175)

2023-11-30 01:16 UTC, lizhijie429 commented on packages/common/component/MetaHtmlText.vue
> +  <div>
不加额外加这一层 div，Vue3透传Attributes机制也没有办法确定要在哪一个根节点继承属性所以出现了上述警告。

三种解决办法：
第一种：在使用setup语法糖的情况下注意使用defineProps接收所有props属性数据。
第二种：确确实实需要传递一个非prop属性数据到子组件中，但子组件中存在多个根节点，则可以在该根节点使用v-bind="$attrs"进行显式绑定，可避免报错了。
第三种：确保子组件中只存在一个根节点。

2023-11-30 01:44 UTC, lizhijie429 commented on packages/common/component/MetaHtmlText.vue
> +  <div>
关于解决透传Attributes警告，这个文件外面包一层div确实不是最好的解决办法，应该 在<div class="attr-list">节点上使用 v-bind="$attrs"解决。

2023-11-30 01:45 UTC, lizhijie429 commented on packages/common/component/MetaHtmlAttributes.vue
> +  <div>
关于解决透传Attributes警告，这个文件外面包一层div确实不是最好的解决办法，应该 在<div class="attr-list">节点上使用 v-bind="$attrs"解决。

2023-11-30 03:09 UTC, chilingling commented on packages/common/component/MetaHtmlAttributes.vue
> +  <div>
对的，可以使用 `v-bind` 进行绑定，但是这里可能不需要使用透传的 attr，我们可以直接声明不绑定 attr: `inheritAttrs: false`

2023-11-30 06:06 UTC, lizhijie429 commented on packages/common/component/MetaHtmlAttributes.vue
> +  <div>
已经按照建议修改并提交。

2023-11-30 06:13 UTC, chilingling approved these changes

2023-11-30 06:14 UTC, chilingling approved these changes
LGTM

2023-11-30 06:22 UTC, wenmine approved these changes

2023-11-30 06:23 UTC, merged