fix: 修复画布宽度设置问题
opentiny/tiny-engine pull request #128
Opened 2023-12-06 07:16 UTC by gene9831

English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Background and solution

### What is the current behavior?

Issue Number: #120 

### What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-12-06 07:37 UTC, chilingling commented on packages/toolbars/media/src/Main.vue
>          case 1200 < Number(state.width) && Number(state.width) <= 1920:
`Number(state.width)` 这个可以存一个变量，避免每个 case 里面都去转化一次

2023-12-11 03:39 UTC, chilingling requested changes

2023-12-11 03:39 UTC, chilingling commented on packages/toolbars/media/src/Main.vue
>      const widthChange = (val) => {
一整个函数圈复杂度高了，建议抽取逻辑出来

2023-12-11 06:44 UTC, chilingling approved these changes, later dismissed

2023-12-15 08:20 UTC, wenmine commented on packages/toolbars/media/src/Main.vue
> +      const reg = '^[0-9]+$'
这个正则可以抽成一个全局constant吗，下面也用到了相同的正则，可以抽成一个复用。

2023-12-15 08:49 UTC, gene9831 commented on packages/toolbars/media/src/Main.vue
> +      const reg = '^[0-9]+$'
缩放 `scale` 可以带小数，应该修改缩放的正则表达式：`'^[0-9]+(\.[0-9]+)?$'`

2023-12-18 11:55 UTC, hexqi commented on packages/toolbars/media/src/Main.vue
> +      const reg = '^[0-9]+(\\.[0-9]+)?$'
建议不用字符串，直接写正则表达式： `/^\d+(\.\d+)?$/`

2023-12-18 12:04 UTC, hexqi commented on packages/toolbars/media/src/Main.vue
> +      const deviceType = dimension.value.deviceType
这里看起来没必要用watchEffect，watch dimension.value.deviceType就行了

2023-12-18 12:08 UTC, hexqi commented on packages/toolbars/media/src/Main.vue
>        () => useLayout().getDimension().width,
可以跟其他地方统一，写成：dimension.value.width

2023-12-18 12:11 UTC, hexqi commented on packages/toolbars/media/src/Main.vue
> +    const breakpoints = [
![image](https://github.com/opentiny/tiny-engine/assets/18585869/613481d8-fabd-4e4c-a00c-a3603b794673)
可以记一个历史遗留问题

2023-12-18 12:16 UTC, hexqi approved these changes

2023-12-18 12:48 UTC, gene9831 commented on packages/toolbars/media/src/Main.vue
> +    const breakpoints = [
#172 跟踪此问题

2023-12-19 00:52 UTC, chilingling approved these changes

2023-12-19 06:43 UTC, merged