Fix/utils cdn
opentiny/tiny-engine pull request #133
Opened 2023-12-07 09:42 UTC by gene9831

[English](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE.md) | 简体中文

# PR

## PR Checklist

请检查您的 PR 是否满足以下要求：

- [x] commit message遵循我们的[提交贡献指南](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] 添加了更改内容的测试用例（用于bugfix/功能）
- [ ] 文档已添加/更新（用于bugfix/功能）
- [ ] 是否构建了自己的设计器，经过了充分的自验证

## PR 类型

这个PR的类型是？

- [x] 日常 bug 修复
- [ ] 新特性支持
- [ ] 代码风格优化
- [ ] 重构
- [ ] 构建优化
- [ ] 测试用例
- [ ] 文档更新
- [ ] 分支合并
- [ ] 其他改动（请补充）

## 需求背景和解决方案

添加有cdn链接的工具类后，使用 `this.utils.xxx` 不生效。
解决方案：使用import函数动态导入esm模块

UI修改：工具类删除按钮添加了校验，禁止删除已使用到的工具类变量

Issue Number: N/A

### 修改前

### 修改后

## 此PR是否含有 breaking change?

- [ ] 是
- [ ] 否

## Other information

2023-12-19 11:42 UTC, chilingling requested changes

2023-12-19 11:42 UTC, chilingling commented on packages/plugins/bridge/src/BridgeSetting.vue
> +  background-color: #f0f0f0;
需要适配一下暗色主题

2023-12-19 11:46 UTC, kevinmoch commented on packages/plugins/bridge/src/BridgeSetting.vue
> +        message: '如果您删除了正在使用的资源，将无法正常预览页面。您确认要删除吗？',
提示语句建议改为：如果删除正在使用的资源，将无法正常预览页面，确认要删除吗？

2023-12-19 12:09 UTC, kevinmoch commented on packages/common/component/SvgButton.vue
>      const isTinyIcon = computed(() => props.name.toLowerCase().indexOf('icon') === 0)
在 name 的默认值是 'add' 的情况下，似乎 isTinyIcon 的计算始终会返回 false。

2023-12-20 06:16 UTC, gene9831 commented on packages/common/component/SvgButton.vue
>      const isTinyIcon = computed(() => props.name.toLowerCase().indexOf('icon') === 0)
`SvgButton` 是使用到了两种 `icon`。一种是 `TinyIcon`，另一种是 `<svg-icon></svg-icon>`。这里是根据传入的 `name` 是否包含字符串 `'icon'` 来判断使用哪一种

2023-12-20 09:19 UTC, kevinmoch submitted a review, later dismissed

2023-12-22 03:08 UTC, chilingling approved these changes

2023-12-22 08:26 UTC, yaoyun8 approved these changes
LGTM

2023-12-22 09:29 UTC, merged