添加style变量赋值
opentiny/tiny-engine pull request #154
Opened 2023-12-14 10:26 UTC by Xppp0217

English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Background and solution

### What is the current behavior?

Issue Number: N/A

### What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-12-14 11:12 UTC, chilingling requested changes

2023-12-14 11:12 UTC, chilingling commented on packages/settings/styles/src/Main.vue
> +        background: #1476ff;
需要兼容暗色模式

2023-12-14 11:12 UTC, chilingling commented on packages/settings/styles/src/Main.vue
> +      <span style="display: block; margin-top: 16px; margin-bottom: 8px; color: #595959; font-size: 12px">
为什么要用行内样式？

2023-12-14 11:12 UTC, chilingling commented on packages/common/component/MetaBindVariable.vue
> +      emit('update:modelValue', 'remove')
这个改动对其他依赖该组件的功能会有影响吗？

2023-12-22 03:04 UTC, chilingling commented on packages/settings/styles/src/Main.vue
> +}
这里是多了一个分号还是格式化不对？

2023-12-22 03:14 UTC, Xppp0217 commented on packages/common/component/MetaBindVariable.vue
> +      emit('update:modelValue', 'remove')
目前看并无影响

2023-12-22 03:16 UTC, Xppp0217 commented on packages/settings/styles/src/Main.vue
> +}
格式化问题

2023-12-22 03:49 UTC, chilingling commented on packages/common/component/MetaBindVariable.vue
> +      emit('update:modelValue', 'remove')
![image](https://github.com/opentiny/tiny-engine/assets/26962197/6be1d491-fd32-4c5f-ae09-bde5b3fd6c57)

这个会影响组件绑定，复现逻辑：
1. 属性面板点击绑定属性，随便绑定一个变量
![image](https://github.com/opentiny/tiny-engine/assets/26962197/ab5e7da8-ea8d-4d9f-a73d-23226e159a9c)

2.  绑定后再次点击绑定变量弹窗，点击移除绑定
![image](https://github.com/opentiny/tiny-engine/assets/26962197/60f8962e-ed40-4500-923f-ff80bf98e4b0)

移除绑定后会导致并没有清除绑定，而是出来 remove 值

2023-12-25 01:30 UTC, chilingling commented on packages/settings/styles/src/Main.vue
> +      () => {
可以简化成 `() => getCurrentSchema()`

2023-12-25 03:34 UTC, chilingling commented on packages/settings/styles/src/Main.vue
> +        if (val?.props && val.props?.style?.value) {
`if (val?.props?.style?.value) {` 就可以了

2023-12-25 06:17 UTC, chilingling approved these changes

2023-12-26 01:02 UTC, merged