fix(configItem): 属性里添加Reset功能
opentiny/tiny-engine pull request #186
Opened 2023-12-23 09:15 UTC by wenmine

[English](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE.md) | 简体中文

# PR

## PR Checklist

请检查您的 PR 是否满足以下要求：

- [ ] commit message遵循我们的[提交贡献指南](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] 添加了更改内容的测试用例（用于bugfix/功能）
- [ ] 文档已添加/更新（用于bugfix/功能）
- [ ] 是否构建了自己的设计器，经过了充分的自验证

## PR 类型

这个PR的类型是？

- [ ] 日常 bug 修复
- [ ] 新特性支持
- [ ] 代码风格优化
- [ ] 重构
- [ ] 构建优化
- [ ] 测试用例
- [ ] 文档更新
- [ ] 分支合并
- [ ] 其他改动（请补充）

## 需求背景和解决方案

Issue Number: N/A

### 修改前

### 修改后

## 此PR是否含有 breaking change?

- [ ] 是
- [ ] 否

## Other information

2023-12-26 03:28 UTC, yaoyun8 commented on packages/common/component/ConfigItem.vue
> +    const canOpenResetSetting = () => isValueChanged.value && canResetComponents(widget.value.component)
可以定义为computed

2023-12-26 03:47 UTC, yaoyun8 commented on packages/common/component/PanelModalMask.vue
> +    left: calc(100% - var(--lowcode-setting-panel-min-width));
这个宽度好像要小一点，真实宽度是上面的--base-right-panel-width

2024-01-09 02:19 UTC, wenmine commented on packages/common/component/PanelModalMask.vue
> +    left: calc(100% - var(--lowcode-setting-panel-min-width));
现状是真实宽度是 --lowcode-setting-panel-min-width，因为--lowcode-setting-panel-min-width比--base-right-panel-width 要大

2024-01-16 06:17 UTC, yaoyun8 commented on packages/common/component/PanelModalMask.vue
> +    left: calc(100% - var(--lowcode-setting-panel-min-width));
--lowcode-setting-panel-min-width 好像已经清理掉了

2024-01-24 03:23 UTC, yaoyun8 submitted a review, later dismissed
LGTM

2024-01-24 09:16 UTC, chilingling requested changes

2024-01-24 09:16 UTC, chilingling commented on packages/common/component/ConfigItem.vue
> +    const initValue = bindValue.value
这里的属性重置应该是将属性清空，而不是重置到原来的值。
重置到原来的值的话，第二次进来，值就无法重置了。

2024-01-26 02:11 UTC, chilingling commented on packages/common/component/ConfigItem.vue
> +  <modal-mask v-if="showModal" @close="showModal = false" class="reset-mask">
`@close` 属性放到最后
`<modal-mask v-if="showModal" class="reset-mask" @close="showModal = false">`

2024-01-26 02:11 UTC, chilingling commented on packages/common/component/ConfigItem.vue
>  import { useHistory, useProperties, useResource, useLayout, useCanvas } from '@opentiny/tiny-engine-controller'
这里帮忙顺便修复一下依赖声明顺序

2024-05-17 09:42 UTC, closed without merging