docs: add project name to issue template
opentiny/tiny-engine pull request #335
Opened 2024-03-14 08:18 UTC by kagol

English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Background and solution

### What is the current behavior?

Issue Number: N/A

### What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-03-16 09:48 UTC, chilingling approved these changes

2024-03-16 09:51 UTC, chilingling requested changes

2024-03-16 09:51 UTC, chilingling commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      description: We also welcome you to fill in more detailed project information in the following issue [#334](https://github.com/opentiny/tiny-vue/issues/334).
这里要改成 tiny-engine 的 issue 链接，下同

2024-03-20 11:25 UTC, chilingling approved these changes

2024-03-21 14:17 UTC, rhlin approved these changes

2024-03-27 01:26 UTC, merged