fix(dsl-page):修复对于props属性引用utils出码报错的问题
opentiny/tiny-engine pull request #346
Opened 2024-03-20 08:58 UTC by wenmine

[English](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE.md) | 简体中文

# PR

## PR Checklist

请检查您的 PR 是否满足以下要求：

- [ ] commit message遵循我们的[提交贡献指南](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] 添加了更改内容的测试用例（用于bugfix/功能）
- [ ] 文档已添加/更新（用于bugfix/功能）
- [ ] 是否构建了自己的设计器，经过了充分的自验证

## PR 类型

这个PR的类型是？

- [ ] 日常 bug 修复
- [ ] 新特性支持
- [ ] 代码风格优化
- [ ] 重构
- [ ] 构建优化
- [ ] 测试用例
- [ ] 文档更新
- [ ] 分支合并
- [ ] 其他改动（请补充）

## 需求背景和解决方案
问题发现来源：在定位#323问题时，先启动自己本地+mockServer定位，发现无法复现用户问题，但是有当前这个问题出现。

问题现象：给物料的props属性，如：id，进行变量绑定，绑定一个工具类时，在画布阶段能够正常使用，但是在预览阶段，会报错。
复现步骤：
![image](https://github.com/opentiny/tiny-engine/assets/14882982/45cd6089-0d01-4dfd-8f8b-c57db3d199b2)

点击保存，预览

具体报错内容如下：

![image](https://github.com/opentiny/tiny-engine/assets/14882982/ce2a8666-a4c7-4822-bd23-9e15dc9f6f9e)
![image](https://github.com/opentiny/tiny-engine/assets/14882982/2918b1bf-51ad-45a9-b7c4-528de16120ad)

定位后发现在DSL中，对于JSExpression的添加，只会在schema结构中被children包裹的情况，如
![image](https://github.com/opentiny/tiny-engine/assets/14882982/fae24c61-8145-486a-85c8-7d93024adc37)

而对于props属性，并没有被children包裹，那这一块内容会被忽略掉
![image](https://github.com/opentiny/tiny-engine/assets/14882982/fec3b86c-cb36-491b-91b7-eb7a994deebb)

Issue Number: #323 

### 修改前
预览报错，无法预览

### 修改后

可正常预览

## 此PR是否含有 breaking change?

- [ ] 是
- [x] 否

## Other information

2024-03-27 09:22 UTC, rhlin commented on packages/vue-generator/src/generator/page.js
> +          description.jsResource[jsResourceKey] || item.value.includes(`.${jsResourceKey}.`)
`item.value.includes(`.${jsResourceKey}.`` 是否会有误命中的场景

2024-03-29 02:08 UTC, wenmine commented on packages/vue-generator/src/generator/page.js
> +          description.jsResource[jsResourceKey] || item.value.includes(`.${jsResourceKey}.`)
这个是针对当前出码的修复，后面可以看一下重构后的出码，应该会避免掉这个问题。目前出码现状是其他地方也是用的这样的判断逻辑

2024-03-30 03:21 UTC, rhlin commented on packages/vue-generator/src/generator/page.js
> +          description.jsResource[jsResourceKey] || item.value.includes(`.${jsResourceKey}.`)
好的， 目前没有触发问题，那就先遗留吧

2024-03-30 06:54 UTC, kevinmoch requested changes
代码有性能问题且遗漏场景，需要优化

2024-03-30 06:54 UTC, kevinmoch commented on packages/vue-generator/src/generator/page.js
> +          description.jsResource[jsResourceKey] || item.value.includes(`.${jsResourceKey}.`)
此处存在两个问题：
1、两重嵌套循环，一次是forEach，另一次是includes，存在性能问题
2、没有考虑 jsResourceKey 作为结尾的场景，比如 props.key，只考虑了 props.key.value 中间场景

优化后代码
```js
Object.assign(jsResource, Object.fromEntries(itemValue.split('.').slice(1).map((key) => [key, true])))
````
使用字符串分割成数组，重新构建对象，再进行对象的合并

2024-04-19 09:56 UTC, rhlin approved these changes
LGTM

2024-04-22 03:35 UTC, kevinmoch approved these changes

2024-04-22 03:36 UTC, merged