fix(save-button-loading): 修复包含发布区块,保存页面/工具类/数据源等按钮在点击到执行完毕期间加载loading的样式
opentiny/tiny-engine pull request #456
Opened 2024-04-28 03:44 UTC by betterdancing

English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Background and solution

### What is the current behavior?
需要调用接口的按钮点击后只有短暂的禁用，且接口调用期间仍可点击

Issue Number: N/A

### What is the new behavior?
需要调用接口的按钮点击后到逻辑执行完之前会禁用，且按钮上会显示loading效果

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-04-28 06:04 UTC, chilingling commented on packages/plugins/bridge/src/BridgeSetting.vue
> +        <!-- <tiny-button class="save-btn" type="primary" @click="save">保存</tiny-button> -->
注释不要保留了

2024-04-28 06:33 UTC, betterdancing commented on packages/plugins/bridge/src/BridgeSetting.vue
> +        <!-- <tiny-button class="save-btn" type="primary" @click="save">保存</tiny-button> -->
已解决

2024-04-28 06:34 UTC, betterdancing commented on packages/plugins/bridge/src/BridgeSetting.vue
> +        <!-- <tiny-button class="save-btn" type="primary" @click="save">保存</tiny-button> -->
> 注释不要保留了

已删除

2024-04-28 07:14 UTC, chilingling requested changes

2024-04-28 07:14 UTC, chilingling commented on packages/utils/src/utils/index.js
> +export const releaseBlockState = ref(false)
状态相关的不要放 utils 这里。

2024-04-28 10:00 UTC, betterdancing commented on packages/utils/src/utils/index.js
> +export const releaseBlockState = ref(false)
> 状态相关的不要放 utils 这里。
已解决

2024-04-28 10:40 UTC, chilingling commented on packages/common/component/LoadingButton.vue
> +  <tiny-button type="info" @click="$emit('save')" :disabled="disabled || loading">
tiny-button 自带 loading 配置，看看能否满足需求，能满足需求就不要再封装一个了

2024-04-28 10:40 UTC, chilingling commented on packages/toolbars/breadcrumb/package.json
> +    "@opentiny/tiny-engine-utils": "workspace:*",
没用到该依赖就删除掉

2024-05-06 03:51 UTC, chilingling approved these changes, later dismissed

2025-06-24 02:19 UTC, closed without merging