Ospp 2024/feat schema render
opentiny/tiny-engine pull request #780
Opened 2024-09-01 09:33 UTC by Fleurxxx

English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Background and solution

### What is the current behavior?

Issue Number: N/A

### What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-09-03 14:19 UTC, CatsAndMice commented
@Fleurxxx 描述要认真写
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/5248e165-9d7d-478d-98d7-34192668b1db">

2024-09-05 04:11 UTC, hexqi commented on packages/plugins/robot/src/Main.vue
> +{
最好是先有一段描述，简短介绍下格式，然后才是下面的这个示例，这样效果可能会好点

2024-09-05 04:13 UTC, hexqi commented on packages/plugins/robot/src/Main.vue
> +  "props": {},
有一些没有必要的信息可以不用在示例里面带上，比如fileName、props

2024-09-05 04:17 UTC, hexqi commented on packages/plugins/robot/src/Main.vue
> +  "state": {
有些字段是生成代码中很关键的，像children，还有几个相对关键的，比如css,state,methods，这些在Prompt中可以介绍下作用和格式；另外有些不需要AI关注的字段其实在示例中可以去掉，比如fileName,props等，后面AI返回结果可以再跟一个默认值做合并

2024-09-05 04:18 UTC, hexqi commented on packages/plugins/robot/src/Main.vue
> +          "componentName": "TinyForm",
关于组件这块的信息也是在Prompt中需要关注的

2024-10-14 14:04 UTC, CatsAndMice approved these changes

2024-10-17 03:47 UTC, Fleurxxx commented
@chilingling 老师可以帮我合入一下这个pr吗

2024-10-17 03:49 UTC, Fleurxxx commented
@hexqi 老师可以帮我合入一下这个pr吗

2024-10-21 12:50 UTC, chilingling approved these changes, later dismissed

2024-10-21 13:14 UTC, hexqi approved these changes

2024-10-21 13:16 UTC, hexqi requested changes
部分commit没有签名

2024-10-22 02:48 UTC, Fleurxxx commented
@hexqi 老师在现在全部签名了

2024-10-22 11:16 UTC, hexqi approved these changes, later dismissed

2024-10-23 02:17 UTC, hexqi approved these changes

2024-10-23 02:17 UTC, merged